### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Jessekay** [CaptainBawa/Awsome-Book-Captain-Mesak#3]
Kindly make sure you use the Class (OOP) instead of the functional programming method to refactor your code.

- The codebase is supposed to be refactored(minimum lines of code) as before but as you may notice you have a whole bunch of lines of code and even more than one file for the code.

**Comment by dagmawiii03** [comment]
Good job in implementing the refactoring project so far and is similar to the given template layout
